In [1]:
############通过训练的模型进行分类（利好／利空，好坏）############     

import pickle
import re
import jieba


In [2]:
# model = pickle.load(open('sa/model','rb'))
# outpath='model0607withFactor'
# outpath='model0307'
outpath='model0607_rf'

model = pickle.load(open(outpath,'rb'))
model

Pipeline(steps=[('vect', CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=0.9, max_features=None, min_df=10,
        ngram_range=(1, 1), preprocessor=None, stop_words=None,
        stri...mators=500, n_jobs=1, oob_score=False, random_state=None,
            verbose=0, warm_start=False))])

In [3]:
stopwordset = set()
with open('sa/jieba_dict/stopwords.txt','r',encoding = 'utf-8') as sw:
    for line in sw:
        stopwordset.add(line.strip('\n'))
        
def seg_sent(art):
    r = '[’!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~]+'  
    art = art.strip()
    art = re.sub(r, '', art)
    l = []
    seg_list = list(jieba.cut(art, cut_all = False))
    for word in seg_list:
        if word not in stopwordset and word != ' ' and word != "\n" and word != "\n\n":
            l.append(word)
    corpus = " ".join(l)
    return corpus

        
def predictForConttent(content):
    cp = seg_sent(content)
    result = model.predict([cp])
#     output = open('file_sa.txt','w')
    rate = model.predict_proba([cp])
    print(rate)
   
#     output.write("负面值2："+str(rate[0][0])+" 正面值2： "+str(rate[0][1]))
    return rate
   

In [4]:

def main(title):
    file = open(title,"r",encoding = 'utf-8')

    article = file.read()

    cp = seg_sent(article)
    
    result = model.predict([cp])
    output = open('file_sa.txt','w')
    if result == 0:
        print ("这是一篇负面新闻")
        output.write("这是一篇负面新闻")
    else:
        print("这是一篇正面新闻")
        output.write("这是一篇正面新闻")
    print('负面值:\t\t','正面值:')
    rate = model.predict_proba([cp])
    print(rate)
    output.write("负面值2："+str(rate[0][0])+" 正面值2： "+str(rate[0][1]))
    return rate
    

In [5]:
# if __name__ == "__main__":
#     import sys
#     import tkinter as tk
#     from tkinter import filedialog

#     root = tk.Tk()
#     root.withdraw()

#     file_path = filedialog.askopenfilename()
#     main(file_path)

In [12]:
article = "安徽新力金融股份有限公司关于子公司涉及业务诉讼的公告"
seg_list = list(jieba.cut(article, cut_all = False))
print(seg_list)
predictForConttent(article)


article = "天夏智慧:关于因控股股东质押股票触及平仓线的停牌公告"
seg_list = list(jieba.cut(article, cut_all = False))
print(seg_list)
predictForConttent(article)


article = "高正信息:关于控股子公司完成工商登记的公告"
seg_list = list(jieba.cut(article, cut_all = False))
print(seg_list)
predictForConttent(article)

article = "关于控股股东提高盈利增长"
seg_list = list(jieba.cut(article, cut_all = False))
print(seg_list)
predictForConttent(article)


article = "公司的公告发撒"
seg_list = list(jieba.cut(article, cut_all = False))
print(seg_list)
predictForConttent(article)


# a = main("/Users/daichanglin/Desktop/igoldenbeta/robotSVN/robot/robot-parent/python/sa/test/rp1")

['安徽', '新', '力', '金融', '股份', '有限公司', '关于', '子公司', '涉及', '业务', '诉讼', '的', '公告']
[[ 0.85459419  0.14540581]]
['天夏', '智慧', ':', '关于', '因', '控股', '股东', '质押', '股票', '触及', '平仓', '线', '的', '停牌', '公告']
[[ 0.94727046  0.05272954]]
['高正', '信息', ':', '关于', '控股', '子公司', '完成', '工商登记', '的', '公告']
[[ 0.48664962  0.51335038]]
['关于', '控股', '股东', '提高', '盈利', '增长']
[[ 0.52083839  0.47916161]]
['公司', '的', '公告', '发撒']
[[ 0.78772801  0.21227199]]


array([[ 0.78772801,  0.21227199]])

In [7]:
# file = open("/Users/daichanglin/Desktop/igoldenbeta/robotSVN/robot/robot-parent/python/sa/test/p1",
#             "r",encoding = 'utf-8')
# article = file.read()
# predictForConttent(article)

# file = open("/Users/daichanglin/Desktop/igoldenbeta/robotSVN/robot/robot-parent/python/sa/test/p2",
#             "r",encoding = 'utf-8')
# article = file.read()
# predictForConttent(article)

# # file = open("/Users/daichanglin/Desktop/igoldenbeta/robotSVN/robot/robot-parent/python/sa/test/rp3",
# #             "r",encoding = 'utf-8')
# # article = file.read()
# # predictForConttent(article)


# file = open("/Users/daichanglin/Desktop/igoldenbeta/robotSVN/robot/robot-parent/python/sa/test/rp1",
#             "r",encoding = 'utf-8')
# article = file.read()
# predictForConttent(article)

# file = open("/Users/daichanglin/Desktop/igoldenbeta/robotSVN/robot/robot-parent/python/sa/test/rp2",
#             "r",encoding = 'utf-8')
# article = file.read()
# predictForConttent(article)

# file = open("/Users/daichanglin/Desktop/igoldenbeta/robotSVN/robot/robot-parent/python/sa/test/rp3",
#             "r",encoding = 'utf-8')
# article = file.read()
# predictForConttent(article)


# file = open("/Users/daichanglin/Desktop/igoldenbeta/robotSVN/robot/robot-parent/python/sa/test/rp4",
#             "r",encoding = 'utf-8')
# article = file.read()
# predictForConttent(article)




# //model1
# [[ 0.45633987  0.54366013]]
# [[ 0.75958081  0.24041919]]
# [[ 0.53703431  0.46296569]]
# [[ 0.50166667  0.49833333]]
# [[ 0.433125  0.566875]]